name: Java CI with Gradle

on: [pull_request, push]

jobs:
  gradle_validation:
    runs-on: ubuntu-latest
    name: Gradle Wrapper Validation
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
